# Header
menu:
  Home: /
  Arquivos: /archives
  Palestras: /presentations
rss: /atom.xml

# Content
excerpt_link: Continuar lendo
fancybox: true

# Sidebar
sidebar: right
widgets:
- about
#- category
- tag
# - tagcloud
#- archive
#- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics: UA-36456065-6
gauges_analytics:
favicon: /css/images/favicon.ico
twitter: 40165407
google_plus: 101430706077212036573
fb_admins: 100001598543061
fb_app_id: 
